- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!dsacdswe1"
    - name: ansible create directory example
      file:
        path: /tmp/devops_directory
        state: directory

