- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "hjebvhjbfdnjvnjnjgfnjnjnmgf"
    - name: ansible create directory example
      file:
        path: /hoe/ubuntu/vijay
        state: directory

