---
- name: test
  hosts: all
  become: yes
  tasks:
    - name: Instalation of postgresql-9.6
      apt:
      name: postgresql-9.6

    - name: start postgresql service
      service: name=postgresql state=restarted enabled=yes
      
#    - name: create a database
#      postgresql_db:
#        name: joshidb2
#        encoding: UTF-8
#        template: template0
#        state: present
#     become_user: postgres
#      become: yes


    - name: create new table
      postgresql_table:
        db: postgres
        table: rtpops
       #columns:
        #- someColumn TEXT COLLATE "C" NOT NULL
        #- anotherColumn TEXT COLLATE "C" PRIMARY KEY
        #- bla BYTEA PRIMARY KEY
        #- CONSTRAINT  mykey PRIMARY KEY (anotherColumn, bla)
      become_user: postgres
      become: yes
      vars:
        ansible_ssh_pipelining: true
        
    #- name: Ensure bash, OpenSSl, and libssl are the latest versions
     # apt: name={{ item }} update_cache=true state=latest
      #with_items:
       # - bash
       # - openssl
      #  - libssl-dev
      #  - libssl-doc
     # tags: packages

    #- name: Install PostgreSQL
     # apt: name={{ item }} update_cache=true state=installed
     # with_items:
      #  - postgresql
      #  - postgresql-contrib
      #  - libpq-dev
     #   - python-psycopg2
    #  tags: packages



    

    

